// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreMVC_Otopark.Models;

namespace NetCoreMVC_Otopark.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200623165323_mvcotoparkmigration")]
    partial class mvcotoparkmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NetCoreMVC_Otopark.Models.Arac", b =>
                {
                    b.Property<int>("AracID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Aktiflik");

                    b.Property<string>("AracPlaka");

                    b.Property<DateTime>("CikisTarihi");

                    b.Property<DateTime>("GirisTarihi");

                    b.HasKey("AracID");

                    b.ToTable("aracs");
                });
#pragma warning restore 612, 618
        }
    }
}
